name: tests

on:
  schedule:
    - cron: '0 11 1 * *'

  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest', 'macos-14']
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        python -m pip install jinja2
        python -m pip install -e .
        python -m pip install cvxopt

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run headless GUI tests
      uses: coactions/setup-xvfb@v1
      with:
        working-directory: ./tests
        timeout-minutes: 10
        run: python -c "from deareis.program import main; from test_gui import setup_headless_tests; setup_headless_tests(); main()"

    - name: Run API tests
      working-directory: ./tests
      timeout-minutes: 10
      run: python -m unittest discover . -v
